### ISSUE TITLE
Error: Error updating the Seal Number reference from express entry: 

### ISSUE THREAD

**Issue by shroeder** [Navegate/Navegate#35]

**Comment by shroeder** [comment]
Sam where are we at on this?  It should be in the references area of the Express panel.  It was thrown last night at 2:24 AM in Asia, could you see if you can replicate this?  Thanks in advance.

**Comment by sam-damico** [comment]
This is happening in the cargo portion of the express panel under the seal: heading. I can get the error to fire if I enter a seal number with spaces in it. This is probably from people accidentally starting or ending with a space and it will be simple to add a regex to remove all the spaces. I am going to also check other places to see if this is happening elsewhere.

**Comment by sam-damico** [comment]
This seems to be happening in pairs, with a minute or less between the two instances. Here is the rest of the error. 

Duplicate GlobalFolderReference Type and Value (Fault Detail is equal to An ExceptionDetail, likely created by IncludeExceptionDetailInFaults=true, whose value is:
System.Exception: Duplicate GlobalFolderReference Type and Value
   at Microsoft.VisualBasic.CompilerServices.Symbols.Container.InvokeMethod(Method TargetProcedure, Object[] Arguments, Boolean[] CopyBack, BindingFlags Flags)
   at Microsoft.VisualBasic.CompilerServices.NewLateBinding.ObjectLateGet(Object Instance, Type Type, String MemberName, Object[] Arguments, String[] ArgumentNames, Type[] TypeArguments, Boolean[] CopyBack)
   at DataService.DataService.UpdateGlobalFolderReference(String sessionguid, Int32 globalfolderid, Int32 globalfolderreferenceid, Byte deleterow, String type, String value, Byte displayreference)
   at SyncInvokeUpdateGlobalFolderReference(Object , Object[] , Object[] )
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
   at System.S...).

**Comment by sam-damico** [comment]
My best guess for this is that somehow there is a duplicate GlobalFolderReference somewhere that is causing this problem. If this is the case then I think I am going to have problems tracking it down. Have we ever seen a similar problem?

**Comment by shroeder** [comment]
Not entirely sure.  We should wait to see if we get similar errors.
